---  
apiVersion: v1  
kind: Service  
metadata:  
  name: hadoop
  labels:  
    app: hadoop  
spec:  
  ports:  
  - name: hdfs
    port: 8020
  - name: datanode
    port: 50075
  clusterIP: None
  selector:  
    app: hadoop
---  

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hadoop-slave
spec:
  serviceName: "hadoop"
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: hadoop-slave
        image: 172.16.234.101:5000/zjy/hadoop:2.7.4
        env:
        - name: CLUSTER_NUMBER
          value: "2"
        ports:
        - containerPort: 22
        - containerPort: 8020
        - containerPort: 8088
        - containerPort: 50010
        - containerPort: 50020
        - containerPort: 50070
        - containerPort: 50075
        volumeMounts:
        - name: pvc
          mountPath: /data/hdfs/datanode
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 2Gi

